/* global expect, is */
/* eslint-env mocha */
/* eslint no-empty-function: 0, no-new-wrappers: 0, no-unused-expressions: 0 */

describe( 'bundle:boolean' , function () {

  it( 'is.boolean' , function () {

    expect( is.boolean( null ) ).to.not.be.ok()
    expect( is.boolean( void 0 ) ).to.not.be.ok()
    expect( is.boolean( 0 ) ).to.not.be.ok()
    expect( is.boolean( 1 ) ).to.not.be.ok()
    expect( is.boolean( 0 / 0 ) ).to.not.be.ok()
    expect( is.boolean( +1 / 0 ) ).to.not.be.ok()
    expect( is.boolean( -1 / 0 ) ).to.not.be.ok()
    expect( is.boolean( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.boolean( new Number( 1 ) ) ).to.not.be.ok()
    expect( is.boolean( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.boolean( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.boolean( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.boolean( '' ) ).to.not.be.ok()
    expect( is.boolean( 'lipsum' ) ).to.not.be.ok()
    expect( is.boolean( new String( '' ) ) ).to.not.be.ok()
    expect( is.boolean( new String( 'lipsum' ) ) ).to.not.be.ok()
    expect( is.boolean( true ) ).to.be.ok()
    expect( is.boolean( false ) ).to.be.ok()
    expect( is.boolean( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.boolean( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.boolean( {} ) ).to.not.be.ok()
    expect( is.boolean( [] ) ).to.not.be.ok()
    expect( is.boolean( arguments ) ).to.not.be.ok()
    expect( is.boolean( function () {} ) ).to.not.be.ok()
    expect( is.boolean( new Date() ) ).to.not.be.ok()
    expect( is.boolean( new Error() ) ).to.not.be.ok()
    expect( is.boolean( /^/ ) ).to.not.be.ok()

    expect( is.not.boolean( null ) ).to.be.ok()
    expect( is.not.boolean( void 0 ) ).to.be.ok()
    expect( is.not.boolean( 0 ) ).to.be.ok()
    expect( is.not.boolean( 1 ) ).to.be.ok()
    expect( is.not.boolean( 0 / 0 ) ).to.be.ok()
    expect( is.not.boolean( +1 / 0 ) ).to.be.ok()
    expect( is.not.boolean( -1 / 0 ) ).to.be.ok()
    expect( is.not.boolean( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.boolean( new Number( 1 ) ) ).to.be.ok()
    expect( is.not.boolean( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.boolean( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.boolean( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.boolean( '' ) ).to.be.ok()
    expect( is.not.boolean( 'lipsum' ) ).to.be.ok()
    expect( is.not.boolean( new String( '' ) ) ).to.be.ok()
    expect( is.not.boolean( new String( 'lipsum' ) ) ).to.be.ok()
    expect( is.not.boolean( true ) ).to.not.be.ok()
    expect( is.not.boolean( false ) ).to.not.be.ok()
    expect( is.not.boolean( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.boolean( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.boolean( {} ) ).to.be.ok()
    expect( is.not.boolean( [] ) ).to.be.ok()
    expect( is.not.boolean( arguments ) ).to.be.ok()
    expect( is.not.boolean( function () {} ) ).to.be.ok()
    expect( is.not.boolean( new Date() ) ).to.be.ok()
    expect( is.not.boolean( new Error() ) ).to.be.ok()
    expect( is.not.boolean( /^/ ) ).to.be.ok()

  } )

  it( 'is.true' , function () {

    expect( is.true( null ) ).to.not.be.ok()
    expect( is.true( void 0 ) ).to.not.be.ok()
    expect( is.true( 0 ) ).to.not.be.ok()
    expect( is.true( 1 ) ).to.not.be.ok()
    expect( is.true( 0 / 0 ) ).to.not.be.ok()
    expect( is.true( +1 / 0 ) ).to.not.be.ok()
    expect( is.true( -1 / 0 ) ).to.not.be.ok()
    expect( is.true( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.true( new Number( 1 ) ) ).to.not.be.ok()
    expect( is.true( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.true( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.true( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.true( '' ) ).to.not.be.ok()
    expect( is.true( 'lipsum' ) ).to.not.be.ok()
    expect( is.true( new String( '' ) ) ).to.not.be.ok()
    expect( is.true( new String( 'lipsum' ) ) ).to.not.be.ok()
    expect( is.true( true ) ).to.be.ok()
    expect( is.true( false ) ).to.not.be.ok()
    expect( is.true( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.true( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.true( {} ) ).to.not.be.ok()
    expect( is.true( [] ) ).to.not.be.ok()
    expect( is.true( arguments ) ).to.not.be.ok()
    expect( is.true( function () {} ) ).to.not.be.ok()
    expect( is.true( new Date() ) ).to.not.be.ok()
    expect( is.true( new Error() ) ).to.not.be.ok()
    expect( is.true( /^/ ) ).to.not.be.ok()

    expect( is.not.true( null ) ).to.be.ok()
    expect( is.not.true( void 0 ) ).to.be.ok()
    expect( is.not.true( 0 ) ).to.be.ok()
    expect( is.not.true( 1 ) ).to.be.ok()
    expect( is.not.true( 0 / 0 ) ).to.be.ok()
    expect( is.not.true( +1 / 0 ) ).to.be.ok()
    expect( is.not.true( -1 / 0 ) ).to.be.ok()
    expect( is.not.true( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.true( new Number( 1 ) ) ).to.be.ok()
    expect( is.not.true( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.true( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.true( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.true( '' ) ).to.be.ok()
    expect( is.not.true( 'lipsum' ) ).to.be.ok()
    expect( is.not.true( new String( '' ) ) ).to.be.ok()
    expect( is.not.true( new String( 'lipsum' ) ) ).to.be.ok()
    expect( is.not.true( true ) ).to.not.be.ok()
    expect( is.not.true( false ) ).to.be.ok()
    expect( is.not.true( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.true( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.true( {} ) ).to.be.ok()
    expect( is.not.true( [] ) ).to.be.ok()
    expect( is.not.true( arguments ) ).to.be.ok()
    expect( is.not.true( function () {} ) ).to.be.ok()
    expect( is.not.true( new Date() ) ).to.be.ok()
    expect( is.not.true( new Error() ) ).to.be.ok()
    expect( is.not.true( /^/ ) ).to.be.ok()

  } )
  it( 'is.false' , function () {

    expect( is.false( null ) ).to.not.be.ok()
    expect( is.false( void 0 ) ).to.not.be.ok()
    expect( is.false( 0 ) ).to.not.be.ok()
    expect( is.false( 1 ) ).to.not.be.ok()
    expect( is.false( 0 / 0 ) ).to.not.be.ok()
    expect( is.false( +1 / 0 ) ).to.not.be.ok()
    expect( is.false( -1 / 0 ) ).to.not.be.ok()
    expect( is.false( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.false( new Number( 1 ) ) ).to.not.be.ok()
    expect( is.false( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.false( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.false( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.false( '' ) ).to.not.be.ok()
    expect( is.false( 'lipsum' ) ).to.not.be.ok()
    expect( is.false( new String( '' ) ) ).to.not.be.ok()
    expect( is.false( new String( 'lipsum' ) ) ).to.not.be.ok()
    expect( is.false( true ) ).to.not.be.ok()
    expect( is.false( false ) ).to.be.ok()
    expect( is.false( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.false( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.false( {} ) ).to.not.be.ok()
    expect( is.false( [] ) ).to.not.be.ok()
    expect( is.false( arguments ) ).to.not.be.ok()
    expect( is.false( function () {} ) ).to.not.be.ok()
    expect( is.false( new Date() ) ).to.not.be.ok()
    expect( is.false( new Error() ) ).to.not.be.ok()
    expect( is.false( /^/ ) ).to.not.be.ok()

    expect( is.not.false( null ) ).to.be.ok()
    expect( is.not.false( void 0 ) ).to.be.ok()
    expect( is.not.false( 0 ) ).to.be.ok()
    expect( is.not.false( 1 ) ).to.be.ok()
    expect( is.not.false( 0 / 0 ) ).to.be.ok()
    expect( is.not.false( +1 / 0 ) ).to.be.ok()
    expect( is.not.false( -1 / 0 ) ).to.be.ok()
    expect( is.not.false( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.false( new Number( 1 ) ) ).to.be.ok()
    expect( is.not.false( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.false( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.false( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.false( '' ) ).to.be.ok()
    expect( is.not.false( 'lipsum' ) ).to.be.ok()
    expect( is.not.false( new String( '' ) ) ).to.be.ok()
    expect( is.not.false( new String( 'lipsum' ) ) ).to.be.ok()
    expect( is.not.false( true ) ).to.be.ok()
    expect( is.not.false( false ) ).to.not.be.ok()
    expect( is.not.false( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.false( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.false( {} ) ).to.be.ok()
    expect( is.not.false( [] ) ).to.be.ok()
    expect( is.not.false( arguments ) ).to.be.ok()
    expect( is.not.false( function () {} ) ).to.be.ok()
    expect( is.not.false( new Date() ) ).to.be.ok()
    expect( is.not.false( new Error() ) ).to.be.ok()
    expect( is.not.false( /^/ ) ).to.be.ok()

  } )

  it( 'is.truthy' , function () {

    expect( is.truthy( null ) ).to.not.be.ok()
    expect( is.truthy( void 0 ) ).to.not.be.ok()
    expect( is.truthy( 0 ) ).to.not.be.ok()
    expect( is.truthy( 1 ) ).to.be.ok()
    expect( is.truthy( 0 / 0 ) ).to.not.be.ok()
    expect( is.truthy( +1 / 0 ) ).to.be.ok()
    expect( is.truthy( -1 / 0 ) ).to.be.ok()
    expect( is.truthy( new Number( 0 ) ) ).to.be.ok()
    expect( is.truthy( new Number( 1 ) ) ).to.be.ok()
    expect( is.truthy( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.truthy( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.truthy( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.truthy( '' ) ).to.not.be.ok()
    expect( is.truthy( 'lipsum' ) ).to.be.ok()
    expect( is.truthy( new String( '' ) ) ).to.be.ok()
    expect( is.truthy( new String( 'lipsum' ) ) ).to.be.ok()
    expect( is.truthy( true ) ).to.be.ok()
    expect( is.truthy( false ) ).to.not.be.ok()
    expect( is.truthy( new Boolean( true ) ) ).to.be.ok()
    expect( is.truthy( new Boolean( false ) ) ).to.be.ok()
    expect( is.truthy( {} ) ).to.be.ok()
    expect( is.truthy( [] ) ).to.be.ok()
    expect( is.truthy( arguments ) ).to.be.ok()
    expect( is.truthy( function () {} ) ).to.be.ok()
    expect( is.truthy( new Date() ) ).to.be.ok()
    expect( is.truthy( new Error() ) ).to.be.ok()
    expect( is.truthy( /^/ ) ).to.be.ok()

    expect( is.not.truthy( null ) ).to.be.ok()
    expect( is.not.truthy( void 0 ) ).to.be.ok()
    expect( is.not.truthy( 0 ) ).to.be.ok()
    expect( is.not.truthy( 1 ) ).to.not.be.ok()
    expect( is.not.truthy( 0 / 0 ) ).to.be.ok()
    expect( is.not.truthy( +1 / 0 ) ).to.not.be.ok()
    expect( is.not.truthy( -1 / 0 ) ).to.not.be.ok()
    expect( is.not.truthy( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.not.truthy( new Number( 1 ) ) ).to.not.be.ok()
    expect( is.not.truthy( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.not.truthy( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.not.truthy( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.not.truthy( '' ) ).to.be.ok()
    expect( is.not.truthy( 'lipsum' ) ).to.not.be.ok()
    expect( is.not.truthy( new String( '' ) ) ).to.not.be.ok()
    expect( is.not.truthy( new String( 'lipsum' ) ) ).to.not.be.ok()
    expect( is.not.truthy( true ) ).to.not.be.ok()
    expect( is.not.truthy( false ) ).to.be.ok()
    expect( is.not.truthy( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.not.truthy( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.not.truthy( {} ) ).to.not.be.ok()
    expect( is.not.truthy( [] ) ).to.not.be.ok()
    expect( is.not.truthy( arguments ) ).to.not.be.ok()
    expect( is.not.truthy( function () {} ) ).to.not.be.ok()
    expect( is.not.truthy( new Date() ) ).to.not.be.ok()
    expect( is.not.truthy( new Error() ) ).to.not.be.ok()
    expect( is.not.truthy( /^/ ) ).to.not.be.ok()

  } )
  it( 'is.falsy' , function () {

    expect( is.falsy( null ) ).to.be.ok()
    expect( is.falsy( void 0 ) ).to.be.ok()
    expect( is.falsy( 0 ) ).to.be.ok()
    expect( is.falsy( 1 ) ).to.not.be.ok()
    expect( is.falsy( 0 / 0 ) ).to.be.ok()
    expect( is.falsy( +1 / 0 ) ).to.not.be.ok()
    expect( is.falsy( -1 / 0 ) ).to.not.be.ok()
    expect( is.falsy( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.falsy( new Number( 1 ) ) ).to.not.be.ok()
    expect( is.falsy( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.falsy( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.falsy( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.falsy( '' ) ).to.be.ok()
    expect( is.falsy( 'lipsum' ) ).to.not.be.ok()
    expect( is.falsy( new String( '' ) ) ).to.not.be.ok()
    expect( is.falsy( new String( 'lipsum' ) ) ).to.not.be.ok()
    expect( is.falsy( true ) ).to.not.be.ok()
    expect( is.falsy( false ) ).to.be.ok()
    expect( is.falsy( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.falsy( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.falsy( {} ) ).to.not.be.ok()
    expect( is.falsy( [] ) ).to.not.be.ok()
    expect( is.falsy( arguments ) ).to.not.be.ok()
    expect( is.falsy( function () {} ) ).to.not.be.ok()
    expect( is.falsy( new Date() ) ).to.not.be.ok()
    expect( is.falsy( new Error() ) ).to.not.be.ok()
    expect( is.falsy( /^/ ) ).to.not.be.ok()

    expect( is.not.falsy( null ) ).to.not.be.ok()
    expect( is.not.falsy( void 0 ) ).to.not.be.ok()
    expect( is.not.falsy( 0 ) ).to.not.be.ok()
    expect( is.not.falsy( 1 ) ).to.be.ok()
    expect( is.not.falsy( 0 / 0 ) ).to.not.be.ok()
    expect( is.not.falsy( +1 / 0 ) ).to.be.ok()
    expect( is.not.falsy( -1 / 0 ) ).to.be.ok()
    expect( is.not.falsy( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.falsy( new Number( 1 ) ) ).to.be.ok()
    expect( is.not.falsy( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.falsy( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.falsy( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.falsy( '' ) ).to.not.be.ok()
    expect( is.not.falsy( 'lipsum' ) ).to.be.ok()
    expect( is.not.falsy( new String( '' ) ) ).to.be.ok()
    expect( is.not.falsy( new String( 'lipsum' ) ) ).to.be.ok()
    expect( is.not.falsy( true ) ).to.be.ok()
    expect( is.not.falsy( false ) ).to.not.be.ok()
    expect( is.not.falsy( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.falsy( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.falsy( {} ) ).to.be.ok()
    expect( is.not.falsy( [] ) ).to.be.ok()
    expect( is.not.falsy( arguments ) ).to.be.ok()
    expect( is.not.falsy( function () {} ) ).to.be.ok()
    expect( is.not.falsy( new Date() ) ).to.be.ok()
    expect( is.not.falsy( new Error() ) ).to.be.ok()
    expect( is.not.falsy( /^/ ) ).to.be.ok()

  } )

} )
