/* global expect, is */
/* eslint-env mocha */
/* eslint no-empty-function: 0, no-new-wrappers: 0, no-unused-expressions: 0 */

describe( 'bundle:nil' , function () {

  it( 'is.null' , function () {

    expect( is.null( null ) ).to.be.ok()
    expect( is.null( void 0 ) ).to.not.be.ok()
    expect( is.null( 0 ) ).to.not.be.ok()
    expect( is.null( 0 / 0 ) ).to.not.be.ok()
    expect( is.null( +1 / 0 ) ).to.not.be.ok()
    expect( is.null( -1 / 0 ) ).to.not.be.ok()
    expect( is.null( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.null( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.null( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.null( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.null( '' ) ).to.not.be.ok()
    expect( is.null( new String( '' ) ) ).to.not.be.ok()
    expect( is.null( true ) ).to.not.be.ok()
    expect( is.null( false ) ).to.not.be.ok()
    expect( is.null( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.null( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.null( {} ) ).to.not.be.ok()
    expect( is.null( [] ) ).to.not.be.ok()
    expect( is.null( arguments ) ).to.not.be.ok()
    expect( is.null( function () {} ) ).to.not.be.ok()
    expect( is.null( new Date() ) ).to.not.be.ok()
    expect( is.null( new Error() ) ).to.not.be.ok()
    expect( is.null( /^/ ) ).to.not.be.ok()

    expect( is.not.null( null ) ).to.not.be.ok()
    expect( is.not.null( void 0 ) ).to.be.ok()
    expect( is.not.null( 0 ) ).to.be.ok()
    expect( is.not.null( 0 / 0 ) ).to.be.ok()
    expect( is.not.null( +1 / 0 ) ).to.be.ok()
    expect( is.not.null( -1 / 0 ) ).to.be.ok()
    expect( is.not.null( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.null( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.null( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.null( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.null( '' ) ).to.be.ok()
    expect( is.not.null( new String( '' ) ) ).to.be.ok()
    expect( is.not.null( true ) ).to.be.ok()
    expect( is.not.null( false ) ).to.be.ok()
    expect( is.not.null( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.null( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.null( {} ) ).to.be.ok()
    expect( is.not.null( [] ) ).to.be.ok()
    expect( is.not.null( arguments ) ).to.be.ok()
    expect( is.not.null( function () {} ) ).to.be.ok()
    expect( is.not.null( new Date() ) ).to.be.ok()
    expect( is.not.null( new Error() ) ).to.be.ok()
    expect( is.not.null( /^/ ) ).to.be.ok()

  } )

  it( 'is.undefined' , function () {

    expect( is.undefined( null ) ).to.not.be.ok()
    expect( is.undefined( void 0 ) ).to.be.ok()
    expect( is.undefined( 0 ) ).to.not.be.ok()
    expect( is.undefined( 0 / 0 ) ).to.not.be.ok()
    expect( is.undefined( +1 / 0 ) ).to.not.be.ok()
    expect( is.undefined( -1 / 0 ) ).to.not.be.ok()
    expect( is.undefined( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.undefined( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.undefined( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.undefined( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.undefined( '' ) ).to.not.be.ok()
    expect( is.undefined( new String( '' ) ) ).to.not.be.ok()
    expect( is.undefined( true ) ).to.not.be.ok()
    expect( is.undefined( false ) ).to.not.be.ok()
    expect( is.undefined( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.undefined( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.undefined( {} ) ).to.not.be.ok()
    expect( is.undefined( [] ) ).to.not.be.ok()
    expect( is.undefined( arguments ) ).to.not.be.ok()
    expect( is.undefined( function () {} ) ).to.not.be.ok()
    expect( is.undefined( new Date() ) ).to.not.be.ok()
    expect( is.undefined( new Error() ) ).to.not.be.ok()
    expect( is.undefined( /^/ ) ).to.not.be.ok()

    expect( is.not.undefined( null ) ).to.be.ok()
    expect( is.not.undefined( void 0 ) ).to.not.be.ok()
    expect( is.not.undefined( 0 ) ).to.be.ok()
    expect( is.not.undefined( 0 / 0 ) ).to.be.ok()
    expect( is.not.undefined( +1 / 0 ) ).to.be.ok()
    expect( is.not.undefined( -1 / 0 ) ).to.be.ok()
    expect( is.not.undefined( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.undefined( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.undefined( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.undefined( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.undefined( '' ) ).to.be.ok()
    expect( is.not.undefined( new String( '' ) ) ).to.be.ok()
    expect( is.not.undefined( true ) ).to.be.ok()
    expect( is.not.undefined( false ) ).to.be.ok()
    expect( is.not.undefined( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.undefined( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.undefined( {} ) ).to.be.ok()
    expect( is.not.undefined( [] ) ).to.be.ok()
    expect( is.not.undefined( arguments ) ).to.be.ok()
    expect( is.not.undefined( function () {} ) ).to.be.ok()
    expect( is.not.undefined( new Date() ) ).to.be.ok()
    expect( is.not.undefined( new Error() ) ).to.be.ok()
    expect( is.not.undefined( /^/ ) ).to.be.ok()

  } )

  it( 'is.nil' , function () {

    expect( is.nil( null ) ).to.be.ok()
    expect( is.nil( void 0 ) ).to.be.ok()
    expect( is.nil( 0 ) ).to.not.be.ok()
    expect( is.nil( 0 / 0 ) ).to.not.be.ok()
    expect( is.nil( +1 / 0 ) ).to.not.be.ok()
    expect( is.nil( -1 / 0 ) ).to.not.be.ok()
    expect( is.nil( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.nil( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.nil( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.nil( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.nil( '' ) ).to.not.be.ok()
    expect( is.nil( new String( '' ) ) ).to.not.be.ok()
    expect( is.nil( true ) ).to.not.be.ok()
    expect( is.nil( false ) ).to.not.be.ok()
    expect( is.nil( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.nil( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.nil( {} ) ).to.not.be.ok()
    expect( is.nil( [] ) ).to.not.be.ok()
    expect( is.nil( arguments ) ).to.not.be.ok()
    expect( is.nil( function () {} ) ).to.not.be.ok()
    expect( is.nil( new Date() ) ).to.not.be.ok()
    expect( is.nil( new Error() ) ).to.not.be.ok()
    expect( is.nil( /^/ ) ).to.not.be.ok()

    expect( is.not.nil( null ) ).to.not.be.ok()
    expect( is.not.nil( void 0 ) ).to.not.be.ok()
    expect( is.not.nil( 0 ) ).to.be.ok()
    expect( is.not.nil( 0 / 0 ) ).to.be.ok()
    expect( is.not.nil( +1 / 0 ) ).to.be.ok()
    expect( is.not.nil( -1 / 0 ) ).to.be.ok()
    expect( is.not.nil( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.nil( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.nil( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.nil( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.nil( '' ) ).to.be.ok()
    expect( is.not.nil( new String( '' ) ) ).to.be.ok()
    expect( is.not.nil( true ) ).to.be.ok()
    expect( is.not.nil( false ) ).to.be.ok()
    expect( is.not.nil( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.nil( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.nil( {} ) ).to.be.ok()
    expect( is.not.nil( [] ) ).to.be.ok()
    expect( is.not.nil( arguments ) ).to.be.ok()
    expect( is.not.nil( function () {} ) ).to.be.ok()
    expect( is.not.nil( new Date() ) ).to.be.ok()
    expect( is.not.nil( new Error() ) ).to.be.ok()
    expect( is.not.nil( /^/ ) ).to.be.ok()

  } )

} )
