/* global expect, is */
/* eslint-env mocha */
/* eslint no-empty-function: 0, no-new-wrappers: 0, no-unused-expressions: 0 */

describe( 'bundle:number' , function () {

  var MAX_SAFE_INTEGER = Number.MAX_SAFE_INTEGER || Math.pow( 2 , 53 ) - 1
  var MIN_SAFE_INTEGER = Number.MIN_SAFE_INTEGER || -MAX_SAFE_INTEGER

  it( 'is.number' , function () {

    expect( is.number( null ) ).to.not.be.ok()
    expect( is.number( void 0 ) ).to.not.be.ok()
    expect( is.number( 0 ) ).to.be.ok()
    expect( is.number( 0 / 0 ) ).to.be.ok()
    expect( is.number( +1 / 0 ) ).to.be.ok()
    expect( is.number( -1 / 0 ) ).to.be.ok()
    expect( is.number( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.number( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.number( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.number( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.number( '' ) ).to.not.be.ok()
    expect( is.number( new String( '' ) ) ).to.not.be.ok()
    expect( is.number( true ) ).to.not.be.ok()
    expect( is.number( false ) ).to.not.be.ok()
    expect( is.number( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.number( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.number( {} ) ).to.not.be.ok()
    expect( is.number( [] ) ).to.not.be.ok()
    expect( is.number( arguments ) ).to.not.be.ok()
    expect( is.number( function () {} ) ).to.not.be.ok()
    expect( is.number( new Date() ) ).to.not.be.ok()
    expect( is.number( new Error() ) ).to.not.be.ok()
    expect( is.number( /^/ ) ).to.not.be.ok()

    expect( is.not.number( null ) ).to.be.ok()
    expect( is.not.number( void 0 ) ).to.be.ok()
    expect( is.not.number( 0 ) ).to.not.be.ok()
    expect( is.not.number( 0 / 0 ) ).to.not.be.ok()
    expect( is.not.number( +1 / 0 ) ).to.not.be.ok()
    expect( is.not.number( -1 / 0 ) ).to.not.be.ok()
    expect( is.not.number( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.number( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.number( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.number( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.number( '' ) ).to.be.ok()
    expect( is.not.number( new String( '' ) ) ).to.be.ok()
    expect( is.not.number( true ) ).to.be.ok()
    expect( is.not.number( false ) ).to.be.ok()
    expect( is.not.number( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.number( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.number( {} ) ).to.be.ok()
    expect( is.not.number( [] ) ).to.be.ok()
    expect( is.not.number( arguments ) ).to.be.ok()
    expect( is.not.number( function () {} ) ).to.be.ok()
    expect( is.not.number( new Date() ) ).to.be.ok()
    expect( is.not.number( new Error() ) ).to.be.ok()
    expect( is.not.number( /^/ ) ).to.be.ok()

  } )

  it( 'is.nan' , function () {

    expect( is.nan( null ) ).to.not.be.ok()
    expect( is.nan( void 0 ) ).to.not.be.ok()
    expect( is.nan( 0 ) ).to.not.be.ok()
    expect( is.nan( 0 / 0 ) ).to.be.ok()
    expect( is.nan( +1 / 0 ) ).to.not.be.ok()
    expect( is.nan( -1 / 0 ) ).to.not.be.ok()
    expect( is.nan( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.nan( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.nan( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.nan( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.nan( '' ) ).to.not.be.ok()
    expect( is.nan( new String( '' ) ) ).to.not.be.ok()
    expect( is.nan( true ) ).to.not.be.ok()
    expect( is.nan( false ) ).to.not.be.ok()
    expect( is.nan( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.nan( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.nan( {} ) ).to.not.be.ok()
    expect( is.nan( [] ) ).to.not.be.ok()
    expect( is.nan( arguments ) ).to.not.be.ok()
    expect( is.nan( function () {} ) ).to.not.be.ok()
    expect( is.nan( new Date() ) ).to.not.be.ok()
    expect( is.nan( new Error() ) ).to.not.be.ok()
    expect( is.nan( /^/ ) ).to.not.be.ok()

    expect( is.not.nan( null ) ).to.be.ok()
    expect( is.not.nan( void 0 ) ).to.be.ok()
    expect( is.not.nan( 0 ) ).to.be.ok()
    expect( is.not.nan( 0 / 0 ) ).to.not.be.ok()
    expect( is.not.nan( +1 / 0 ) ).to.be.ok()
    expect( is.not.nan( -1 / 0 ) ).to.be.ok()
    expect( is.not.nan( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.nan( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.nan( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.nan( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.nan( '' ) ).to.be.ok()
    expect( is.not.nan( new String( '' ) ) ).to.be.ok()
    expect( is.not.nan( true ) ).to.be.ok()
    expect( is.not.nan( false ) ).to.be.ok()
    expect( is.not.nan( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.nan( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.nan( {} ) ).to.be.ok()
    expect( is.not.nan( [] ) ).to.be.ok()
    expect( is.not.nan( arguments ) ).to.be.ok()
    expect( is.not.nan( function () {} ) ).to.be.ok()
    expect( is.not.nan( new Date() ) ).to.be.ok()
    expect( is.not.nan( new Error() ) ).to.be.ok()
    expect( is.not.nan( /^/ ) ).to.be.ok()

  } )

  it( 'is.odd' , function () {

    expect( is.odd( null ) ).to.not.be.ok()
    expect( is.odd( void 0 ) ).to.not.be.ok()
    expect( is.odd( 1 ) ).to.be.ok()
    expect( is.odd( 1.1 ) ).to.not.be.ok()
    expect( is.odd( 2 ) ).to.not.be.ok()
    expect( is.odd( 2.2 ) ).to.not.be.ok()
    expect( is.odd( 0 / 0 ) ).to.not.be.ok()
    expect( is.odd( +1 / 0 ) ).to.not.be.ok()
    expect( is.odd( -1 / 0 ) ).to.not.be.ok()
    expect( is.odd( new Number( 1 ) ) ).to.not.be.ok()
    expect( is.odd( new Number( 1.1 ) ) ).to.not.be.ok()
    expect( is.odd( new Number( 2 ) ) ).to.not.be.ok()
    expect( is.odd( new Number( 2.2 ) ) ).to.not.be.ok()
    expect( is.odd( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.odd( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.odd( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.odd( '' ) ).to.not.be.ok()
    expect( is.odd( '1' ) ).to.not.be.ok()
    expect( is.odd( '2' ) ).to.not.be.ok()
    expect( is.odd( new String( '' ) ) ).to.not.be.ok()
    expect( is.odd( new String( '1' ) ) ).to.not.be.ok()
    expect( is.odd( new String( '2' ) ) ).to.not.be.ok()
    expect( is.odd( true ) ).to.not.be.ok()
    expect( is.odd( false ) ).to.not.be.ok()
    expect( is.odd( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.odd( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.odd( {} ) ).to.not.be.ok()
    expect( is.odd( [] ) ).to.not.be.ok()
    expect( is.odd( arguments ) ).to.not.be.ok()
    expect( is.odd( function () {} ) ).to.not.be.ok()
    expect( is.odd( new Date() ) ).to.not.be.ok()
    expect( is.odd( new Error() ) ).to.not.be.ok()
    expect( is.odd( /^/ ) ).to.not.be.ok()

    expect( is.not.odd( null ) ).to.be.ok()
    expect( is.not.odd( void 0 ) ).to.be.ok()
    expect( is.not.odd( 1 ) ).to.not.be.ok()
    expect( is.not.odd( 1.1 ) ).to.be.ok()
    expect( is.not.odd( 2 ) ).to.be.ok()
    expect( is.not.odd( 2.2 ) ).to.be.ok()
    expect( is.not.odd( 0 / 0 ) ).to.be.ok()
    expect( is.not.odd( +1 / 0 ) ).to.be.ok()
    expect( is.not.odd( -1 / 0 ) ).to.be.ok()
    expect( is.not.odd( new Number( 1 ) ) ).to.be.ok()
    expect( is.not.odd( new Number( 1.1 ) ) ).to.be.ok()
    expect( is.not.odd( new Number( 2 ) ) ).to.be.ok()
    expect( is.not.odd( new Number( 2.2 ) ) ).to.be.ok()
    expect( is.not.odd( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.odd( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.odd( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.odd( '' ) ).to.be.ok()
    expect( is.not.odd( '1' ) ).to.be.ok()
    expect( is.not.odd( '2' ) ).to.be.ok()
    expect( is.not.odd( new String( '' ) ) ).to.be.ok()
    expect( is.not.odd( new String( '1' ) ) ).to.be.ok()
    expect( is.not.odd( new String( '2' ) ) ).to.be.ok()
    expect( is.not.odd( true ) ).to.be.ok()
    expect( is.not.odd( false ) ).to.be.ok()
    expect( is.not.odd( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.odd( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.odd( {} ) ).to.be.ok()
    expect( is.not.odd( [] ) ).to.be.ok()
    expect( is.not.odd( arguments ) ).to.be.ok()
    expect( is.not.odd( function () {} ) ).to.be.ok()
    expect( is.not.odd( new Date() ) ).to.be.ok()
    expect( is.not.odd( new Error() ) ).to.be.ok()
    expect( is.not.odd( /^/ ) ).to.be.ok()

  } )
  it( 'is.even' , function () {

    expect( is.even( null ) ).to.not.be.ok()
    expect( is.even( void 0 ) ).to.not.be.ok()
    expect( is.even( 1 ) ).to.not.be.ok()
    expect( is.even( 1.1 ) ).to.not.be.ok()
    expect( is.even( 2 ) ).to.be.ok()
    expect( is.even( 2.2 ) ).to.not.be.ok()
    expect( is.even( 0 / 0 ) ).to.not.be.ok()
    expect( is.even( +1 / 0 ) ).to.not.be.ok()
    expect( is.even( -1 / 0 ) ).to.not.be.ok()
    expect( is.even( new Number( 1 ) ) ).to.not.be.ok()
    expect( is.even( new Number( 1.1 ) ) ).to.not.be.ok()
    expect( is.even( new Number( 2 ) ) ).to.not.be.ok()
    expect( is.even( new Number( 2.2 ) ) ).to.not.be.ok()
    expect( is.even( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.even( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.even( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.even( '' ) ).to.not.be.ok()
    expect( is.even( '1' ) ).to.not.be.ok()
    expect( is.even( '2' ) ).to.not.be.ok()
    expect( is.even( new String( '' ) ) ).to.not.be.ok()
    expect( is.even( new String( '1' ) ) ).to.not.be.ok()
    expect( is.even( new String( '2' ) ) ).to.not.be.ok()
    expect( is.even( true ) ).to.not.be.ok()
    expect( is.even( false ) ).to.not.be.ok()
    expect( is.even( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.even( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.even( {} ) ).to.not.be.ok()
    expect( is.even( [] ) ).to.not.be.ok()
    expect( is.even( arguments ) ).to.not.be.ok()
    expect( is.even( function () {} ) ).to.not.be.ok()
    expect( is.even( new Date() ) ).to.not.be.ok()
    expect( is.even( new Error() ) ).to.not.be.ok()
    expect( is.even( /^/ ) ).to.not.be.ok()

    expect( is.not.even( null ) ).to.be.ok()
    expect( is.not.even( void 0 ) ).to.be.ok()
    expect( is.not.even( 1 ) ).to.be.ok()
    expect( is.not.even( 1.1 ) ).to.be.ok()
    expect( is.not.even( 2 ) ).to.not.be.ok()
    expect( is.not.even( 2.2 ) ).to.be.ok()
    expect( is.not.even( 0 / 0 ) ).to.be.ok()
    expect( is.not.even( +1 / 0 ) ).to.be.ok()
    expect( is.not.even( -1 / 0 ) ).to.be.ok()
    expect( is.not.even( new Number( 1 ) ) ).to.be.ok()
    expect( is.not.even( new Number( 1.1 ) ) ).to.be.ok()
    expect( is.not.even( new Number( 2 ) ) ).to.be.ok()
    expect( is.not.even( new Number( 2.2 ) ) ).to.be.ok()
    expect( is.not.even( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.even( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.even( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.even( '' ) ).to.be.ok()
    expect( is.not.even( '1' ) ).to.be.ok()
    expect( is.not.even( '2' ) ).to.be.ok()
    expect( is.not.even( new String( '' ) ) ).to.be.ok()
    expect( is.not.even( new String( '1' ) ) ).to.be.ok()
    expect( is.not.even( new String( '2' ) ) ).to.be.ok()
    expect( is.not.even( true ) ).to.be.ok()
    expect( is.not.even( false ) ).to.be.ok()
    expect( is.not.even( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.even( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.even( {} ) ).to.be.ok()
    expect( is.not.even( [] ) ).to.be.ok()
    expect( is.not.even( arguments ) ).to.be.ok()
    expect( is.not.even( function () {} ) ).to.be.ok()
    expect( is.not.even( new Date() ) ).to.be.ok()
    expect( is.not.even( new Error() ) ).to.be.ok()
    expect( is.not.even( /^/ ) ).to.be.ok()

  } )

  it( 'is.finite' , function () {

    expect( is.finite( null ) ).to.not.be.ok()
    expect( is.finite( void 0 ) ).to.not.be.ok()
    expect( is.finite( 0 ) ).to.be.ok()
    expect( is.finite( 0 / 0 ) ).to.not.be.ok()
    expect( is.finite( +1 / 0 ) ).to.not.be.ok()
    expect( is.finite( -1 / 0 ) ).to.not.be.ok()
    expect( is.finite( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.finite( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.finite( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.finite( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.finite( '' ) ).to.not.be.ok()
    expect( is.finite( new String( '' ) ) ).to.not.be.ok()
    expect( is.finite( true ) ).to.not.be.ok()
    expect( is.finite( false ) ).to.not.be.ok()
    expect( is.finite( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.finite( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.finite( {} ) ).to.not.be.ok()
    expect( is.finite( [] ) ).to.not.be.ok()
    expect( is.finite( arguments ) ).to.not.be.ok()
    expect( is.finite( function () {} ) ).to.not.be.ok()
    expect( is.finite( new Date() ) ).to.not.be.ok()
    expect( is.finite( new Error() ) ).to.not.be.ok()
    expect( is.finite( /^/ ) ).to.not.be.ok()

    expect( is.not.finite( null ) ).to.be.ok()
    expect( is.not.finite( void 0 ) ).to.be.ok()
    expect( is.not.finite( 0 ) ).to.not.be.ok()
    expect( is.not.finite( 0 / 0 ) ).to.be.ok()
    expect( is.not.finite( +1 / 0 ) ).to.be.ok()
    expect( is.not.finite( -1 / 0 ) ).to.be.ok()
    expect( is.not.finite( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.finite( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.finite( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.finite( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.finite( '' ) ).to.be.ok()
    expect( is.not.finite( new String( '' ) ) ).to.be.ok()
    expect( is.not.finite( true ) ).to.be.ok()
    expect( is.not.finite( false ) ).to.be.ok()
    expect( is.not.finite( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.finite( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.finite( {} ) ).to.be.ok()
    expect( is.not.finite( [] ) ).to.be.ok()
    expect( is.not.finite( arguments ) ).to.be.ok()
    expect( is.not.finite( function () {} ) ).to.be.ok()
    expect( is.not.finite( new Date() ) ).to.be.ok()
    expect( is.not.finite( new Error() ) ).to.be.ok()
    expect( is.not.finite( /^/ ) ).to.be.ok()

  } )
  it( 'is.infinite' , function () {

    expect( is.infinite( null ) ).to.not.be.ok()
    expect( is.infinite( void 0 ) ).to.not.be.ok()
    expect( is.infinite( 0 ) ).to.not.be.ok()
    expect( is.infinite( 0 / 0 ) ).to.not.be.ok()
    expect( is.infinite( +1 / 0 ) ).to.be.ok()
    expect( is.infinite( -1 / 0 ) ).to.be.ok()
    expect( is.infinite( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.infinite( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.infinite( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.infinite( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.infinite( '' ) ).to.not.be.ok()
    expect( is.infinite( new String( '' ) ) ).to.not.be.ok()
    expect( is.infinite( true ) ).to.not.be.ok()
    expect( is.infinite( false ) ).to.not.be.ok()
    expect( is.infinite( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.infinite( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.infinite( {} ) ).to.not.be.ok()
    expect( is.infinite( [] ) ).to.not.be.ok()
    expect( is.infinite( arguments ) ).to.not.be.ok()
    expect( is.infinite( function () {} ) ).to.not.be.ok()
    expect( is.infinite( new Date() ) ).to.not.be.ok()
    expect( is.infinite( new Error() ) ).to.not.be.ok()
    expect( is.infinite( /^/ ) ).to.not.be.ok()

    expect( is.not.infinite( null ) ).to.be.ok()
    expect( is.not.infinite( void 0 ) ).to.be.ok()
    expect( is.not.infinite( 0 ) ).to.be.ok()
    expect( is.not.infinite( 0 / 0 ) ).to.be.ok()
    expect( is.not.infinite( +1 / 0 ) ).to.not.be.ok()
    expect( is.not.infinite( -1 / 0 ) ).to.not.be.ok()
    expect( is.not.infinite( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.infinite( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.infinite( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.infinite( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.infinite( '' ) ).to.be.ok()
    expect( is.not.infinite( new String( '' ) ) ).to.be.ok()
    expect( is.not.infinite( true ) ).to.be.ok()
    expect( is.not.infinite( false ) ).to.be.ok()
    expect( is.not.infinite( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.infinite( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.infinite( {} ) ).to.be.ok()
    expect( is.not.infinite( [] ) ).to.be.ok()
    expect( is.not.infinite( arguments ) ).to.be.ok()
    expect( is.not.infinite( function () {} ) ).to.be.ok()
    expect( is.not.infinite( new Date() ) ).to.be.ok()
    expect( is.not.infinite( new Error() ) ).to.be.ok()
    expect( is.not.infinite( /^/ ) ).to.be.ok()

  } )

  it( 'is.integer' , function () {

    expect( is.integer( null ) ).to.not.be.ok()
    expect( is.integer( void 0 ) ).to.not.be.ok()
    expect( is.integer( 0 ) ).to.be.ok()
    expect( is.integer( 0.1 ) ).to.not.be.ok()
    expect( is.integer( 0 / 0 ) ).to.not.be.ok()
    expect( is.integer( +1 / 0 ) ).to.not.be.ok()
    expect( is.integer( -1 / 0 ) ).to.not.be.ok()
    expect( is.integer( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.integer( new Number( 0.1 ) ) ).to.not.be.ok()
    expect( is.integer( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.integer( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.integer( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.integer( '' ) ).to.not.be.ok()
    expect( is.integer( new String( '' ) ) ).to.not.be.ok()
    expect( is.integer( true ) ).to.not.be.ok()
    expect( is.integer( false ) ).to.not.be.ok()
    expect( is.integer( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.integer( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.integer( {} ) ).to.not.be.ok()
    expect( is.integer( [] ) ).to.not.be.ok()
    expect( is.integer( arguments ) ).to.not.be.ok()
    expect( is.integer( function () {} ) ).to.not.be.ok()
    expect( is.integer( new Date() ) ).to.not.be.ok()
    expect( is.integer( new Error() ) ).to.not.be.ok()
    expect( is.integer( /^/ ) ).to.not.be.ok()

    expect( is.not.integer( null ) ).to.be.ok()
    expect( is.not.integer( void 0 ) ).to.be.ok()
    expect( is.not.integer( 0 ) ).to.not.be.ok()
    expect( is.not.integer( 0.1 ) ).to.be.ok()
    expect( is.not.integer( 0 / 0 ) ).to.be.ok()
    expect( is.not.integer( +1 / 0 ) ).to.be.ok()
    expect( is.not.integer( -1 / 0 ) ).to.be.ok()
    expect( is.not.integer( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.integer( new Number( 0.1 ) ) ).to.be.ok()
    expect( is.not.integer( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.integer( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.integer( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.integer( '' ) ).to.be.ok()
    expect( is.not.integer( new String( '' ) ) ).to.be.ok()
    expect( is.not.integer( true ) ).to.be.ok()
    expect( is.not.integer( false ) ).to.be.ok()
    expect( is.not.integer( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.integer( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.integer( {} ) ).to.be.ok()
    expect( is.not.integer( [] ) ).to.be.ok()
    expect( is.not.integer( arguments ) ).to.be.ok()
    expect( is.not.integer( function () {} ) ).to.be.ok()
    expect( is.not.integer( new Date() ) ).to.be.ok()
    expect( is.not.integer( new Error() ) ).to.be.ok()
    expect( is.not.integer( /^/ ) ).to.be.ok()

  } )
  it( 'is.safeInteger' , function () {

    expect( is.safeInteger( null ) ).to.not.be.ok()
    expect( is.safeInteger( void 0 ) ).to.not.be.ok()
    expect( is.safeInteger( 0 ) ).to.be.ok()
    expect( is.safeInteger( 0.1 ) ).to.not.be.ok()
    expect( is.safeInteger( MAX_SAFE_INTEGER ) ).to.be.ok()
    expect( is.safeInteger( MAX_SAFE_INTEGER + 1 ) ).to.not.be.ok()
    expect( is.safeInteger( MIN_SAFE_INTEGER ) ).to.be.ok()
    expect( is.safeInteger( MIN_SAFE_INTEGER - 1 ) ).to.not.be.ok()
    expect( is.safeInteger( 0 / 0 ) ).to.not.be.ok()
    expect( is.safeInteger( +1 / 0 ) ).to.not.be.ok()
    expect( is.safeInteger( -1 / 0 ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( 0.1 ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( MAX_SAFE_INTEGER ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( MAX_SAFE_INTEGER + 1 ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( MIN_SAFE_INTEGER ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( MIN_SAFE_INTEGER - 1 ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.safeInteger( '' ) ).to.not.be.ok()
    expect( is.safeInteger( new String( '' ) ) ).to.not.be.ok()
    expect( is.safeInteger( true ) ).to.not.be.ok()
    expect( is.safeInteger( false ) ).to.not.be.ok()
    expect( is.safeInteger( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.safeInteger( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.safeInteger( {} ) ).to.not.be.ok()
    expect( is.safeInteger( [] ) ).to.not.be.ok()
    expect( is.safeInteger( arguments ) ).to.not.be.ok()
    expect( is.safeInteger( function () {} ) ).to.not.be.ok()
    expect( is.safeInteger( new Date() ) ).to.not.be.ok()
    expect( is.safeInteger( new Error() ) ).to.not.be.ok()
    expect( is.safeInteger( /^/ ) ).to.not.be.ok()

    expect( is.not.safeInteger( null ) ).to.be.ok()
    expect( is.not.safeInteger( void 0 ) ).to.be.ok()
    expect( is.not.safeInteger( 0 ) ).to.not.be.ok()
    expect( is.not.safeInteger( 0.1 ) ).to.be.ok()
    expect( is.not.safeInteger( MAX_SAFE_INTEGER ) ).to.not.be.ok()
    expect( is.not.safeInteger( MAX_SAFE_INTEGER + 1 ) ).to.be.ok()
    expect( is.not.safeInteger( MIN_SAFE_INTEGER ) ).to.not.be.ok()
    expect( is.not.safeInteger( MIN_SAFE_INTEGER - 1 ) ).to.be.ok()
    expect( is.not.safeInteger( 0 / 0 ) ).to.be.ok()
    expect( is.not.safeInteger( +1 / 0 ) ).to.be.ok()
    expect( is.not.safeInteger( -1 / 0 ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( 0.1 ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( MAX_SAFE_INTEGER ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( MAX_SAFE_INTEGER + 1 ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( MIN_SAFE_INTEGER ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( MIN_SAFE_INTEGER - 1 ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.safeInteger( '' ) ).to.be.ok()
    expect( is.not.safeInteger( new String( '' ) ) ).to.be.ok()
    expect( is.not.safeInteger( true ) ).to.be.ok()
    expect( is.not.safeInteger( false ) ).to.be.ok()
    expect( is.not.safeInteger( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.safeInteger( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.safeInteger( {} ) ).to.be.ok()
    expect( is.not.safeInteger( [] ) ).to.be.ok()
    expect( is.not.safeInteger( arguments ) ).to.be.ok()
    expect( is.not.safeInteger( function () {} ) ).to.be.ok()
    expect( is.not.safeInteger( new Date() ) ).to.be.ok()
    expect( is.not.safeInteger( new Error() ) ).to.be.ok()
    expect( is.not.safeInteger( /^/ ) ).to.be.ok()

  } )

} )
