/* global expect, is */
/* eslint-env mocha */
/* eslint no-empty-function: 0, no-new-wrappers: 0, no-unused-expressions: 0 */

describe( 'bundle:regex' , function () {

  it( 'is.regex' , function () {

    expect( is.regex( null ) ).to.not.be.ok()
    expect( is.regex( void 0 ) ).to.not.be.ok()
    expect( is.regex( 0 ) ).to.not.be.ok()
    expect( is.regex( 0 / 0 ) ).to.not.be.ok()
    expect( is.regex( +1 / 0 ) ).to.not.be.ok()
    expect( is.regex( -1 / 0 ) ).to.not.be.ok()
    expect( is.regex( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.regex( new Number( 0 / 0 ) ) ).to.not.be.ok()
    expect( is.regex( new Number( +1 / 0 ) ) ).to.not.be.ok()
    expect( is.regex( new Number( -1 / 0 ) ) ).to.not.be.ok()
    expect( is.regex( '' ) ).to.not.be.ok()
    expect( is.regex( new String( '' ) ) ).to.not.be.ok()
    expect( is.regex( true ) ).to.not.be.ok()
    expect( is.regex( false ) ).to.not.be.ok()
    expect( is.regex( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.regex( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.regex( {} ) ).to.not.be.ok()
    expect( is.regex( [] ) ).to.not.be.ok()
    expect( is.regex( arguments ) ).to.not.be.ok()
    expect( is.regex( function () {} ) ).to.not.be.ok()
    expect( is.regex( new Date() ) ).to.not.be.ok()
    expect( is.regex( new Error() ) ).to.not.be.ok()
    expect( is.regex( /^/ ) ).to.be.ok()
    expect( is.regex( new RegExp() ) ).to.be.ok()

    expect( is.not.regex( null ) ).to.be.ok()
    expect( is.not.regex( void 0 ) ).to.be.ok()
    expect( is.not.regex( 0 ) ).to.be.ok()
    expect( is.not.regex( 0 / 0 ) ).to.be.ok()
    expect( is.not.regex( +1 / 0 ) ).to.be.ok()
    expect( is.not.regex( -1 / 0 ) ).to.be.ok()
    expect( is.not.regex( new Number( 0 ) ) ).to.be.ok()
    expect( is.not.regex( new Number( 0 / 0 ) ) ).to.be.ok()
    expect( is.not.regex( new Number( +1 / 0 ) ) ).to.be.ok()
    expect( is.not.regex( new Number( -1 / 0 ) ) ).to.be.ok()
    expect( is.not.regex( '' ) ).to.be.ok()
    expect( is.not.regex( new String( '' ) ) ).to.be.ok()
    expect( is.not.regex( true ) ).to.be.ok()
    expect( is.not.regex( false ) ).to.be.ok()
    expect( is.not.regex( new Boolean( true ) ) ).to.be.ok()
    expect( is.not.regex( new Boolean( false ) ) ).to.be.ok()
    expect( is.not.regex( {} ) ).to.be.ok()
    expect( is.not.regex( [] ) ).to.be.ok()
    expect( is.not.regex( arguments ) ).to.be.ok()
    expect( is.not.regex( function () {} ) ).to.be.ok()
    expect( is.not.regex( new Date() ) ).to.be.ok()
    expect( is.not.regex( new Error() ) ).to.be.ok()
    expect( is.not.regex( /^/ ) ).to.not.be.ok()
    expect( is.not.regex( new RegExp() ) ).to.not.be.ok()

  } )

} )
