describe( 'bundle:type' , function () {

  it( 'is.sameType' , function () {

    expect( is.sameType( null , null ) ).to.be.ok()
    expect( is.sameType( null , void 0 ) ).to.not.be.ok()
    expect( is.sameType( null , 0 ) ).to.not.be.ok()
    expect( is.sameType( null , new Number() ) ).to.not.be.ok()
    expect( is.sameType( null , '' ) ).to.not.be.ok()
    expect( is.sameType( null , new String() ) ).to.not.be.ok()
    expect( is.sameType( null , true ) ).to.not.be.ok()
    expect( is.sameType( null , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( null , {} ) ).to.not.be.ok()
    expect( is.sameType( null , [] ) ).to.not.be.ok()
    expect( is.sameType( null , function () {} ) ).to.not.be.ok()
    expect( is.sameType( null , new Date() ) ).to.not.be.ok()
    expect( is.sameType( null , new Error() ) ).to.not.be.ok()
    expect( is.sameType( null , /^/ ) ).to.not.be.ok()

    expect( is.sameType( void 0 , null ) ).to.not.be.ok()
    expect( is.sameType( void 0 , void 0 ) ).to.be.ok()
    expect( is.sameType( void 0 , 0 ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Number() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , '' ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new String() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , true ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , {} ) ).to.not.be.ok()
    expect( is.sameType( void 0 , [] ) ).to.not.be.ok()
    expect( is.sameType( void 0 , function () {} ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Date() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Error() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , /^/ ) ).to.not.be.ok()

    expect( is.sameType( 0 , null ) ).to.not.be.ok()
    expect( is.sameType( 0 , void 0 ) ).to.not.be.ok()
    expect( is.sameType( 0 , 0 ) ).to.be.ok()
    expect( is.sameType( 0 , new Number() ) ).to.not.be.ok()
    expect( is.sameType( 0 , '' ) ).to.not.be.ok()
    expect( is.sameType( 0 , new String() ) ).to.not.be.ok()
    expect( is.sameType( 0 , true ) ).to.not.be.ok()
    expect( is.sameType( 0 , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( 0 , {} ) ).to.not.be.ok()
    expect( is.sameType( 0 , [] ) ).to.not.be.ok()
    expect( is.sameType( 0 , function () {} ) ).to.not.be.ok()
    expect( is.sameType( 0 , new Date() ) ).to.not.be.ok()
    expect( is.sameType( 0 , new Error() ) ).to.not.be.ok()
    expect( is.sameType( 0 , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Number() , null ) ).to.not.be.ok()
    expect( is.sameType( new Number() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Number() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Number() ) ).to.be.ok()
    expect( is.sameType( new Number() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , true ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Number() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Number() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( '' , null ) ).to.not.be.ok()
    expect( is.sameType( '' , void 0 ) ).to.not.be.ok()
    expect( is.sameType( '' , 0 ) ).to.not.be.ok()
    expect( is.sameType( '' , new Number() ) ).to.not.be.ok()
    expect( is.sameType( '' , '' ) ).to.be.ok()
    expect( is.sameType( '' , new String() ) ).to.not.be.ok()
    expect( is.sameType( '' , true ) ).to.not.be.ok()
    expect( is.sameType( '' , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( '' , {} ) ).to.not.be.ok()
    expect( is.sameType( '' , [] ) ).to.not.be.ok()
    expect( is.sameType( '' , function () {} ) ).to.not.be.ok()
    expect( is.sameType( '' , new Date() ) ).to.not.be.ok()
    expect( is.sameType( '' , new Error() ) ).to.not.be.ok()
    expect( is.sameType( '' , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new String() , null ) ).to.not.be.ok()
    expect( is.sameType( new String() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new String() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new String() , '' ) ).to.not.be.ok()
    expect( is.sameType( new String() , new String() ) ).to.be.ok()
    expect( is.sameType( new String() , true ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new String() , {} ) ).to.not.be.ok()
    expect( is.sameType( new String() , [] ) ).to.not.be.ok()
    expect( is.sameType( new String() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new String() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( true , null ) ).to.not.be.ok()
    expect( is.sameType( true , void 0 ) ).to.not.be.ok()
    expect( is.sameType( true , 0 ) ).to.not.be.ok()
    expect( is.sameType( true , new Number() ) ).to.not.be.ok()
    expect( is.sameType( true , '' ) ).to.not.be.ok()
    expect( is.sameType( true , new String() ) ).to.not.be.ok()
    expect( is.sameType( true , true ) ).to.be.ok()
    expect( is.sameType( true , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( true , {} ) ).to.not.be.ok()
    expect( is.sameType( true , [] ) ).to.not.be.ok()
    expect( is.sameType( true , function () {} ) ).to.not.be.ok()
    expect( is.sameType( true , new Date() ) ).to.not.be.ok()
    expect( is.sameType( true , new Error() ) ).to.not.be.ok()
    expect( is.sameType( true , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Boolean() , null ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , true ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Boolean() ) ).to.be.ok()
    expect( is.sameType( new Boolean() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( {} , null ) ).to.not.be.ok()
    expect( is.sameType( {} , void 0 ) ).to.not.be.ok()
    expect( is.sameType( {} , 0 ) ).to.not.be.ok()
    expect( is.sameType( {} , new Number() ) ).to.not.be.ok()
    expect( is.sameType( {} , '' ) ).to.not.be.ok()
    expect( is.sameType( {} , new String() ) ).to.not.be.ok()
    expect( is.sameType( {} , true ) ).to.not.be.ok()
    expect( is.sameType( {} , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( {} , {} ) ).to.be.ok()
    expect( is.sameType( {} , [] ) ).to.not.be.ok()
    expect( is.sameType( {} , function () {} ) ).to.not.be.ok()
    expect( is.sameType( {} , new Date() ) ).to.not.be.ok()
    expect( is.sameType( {} , new Error() ) ).to.not.be.ok()
    expect( is.sameType( {} , /^/ ) ).to.not.be.ok()

    expect( is.sameType( [] , null ) ).to.not.be.ok()
    expect( is.sameType( [] , void 0 ) ).to.not.be.ok()
    expect( is.sameType( [] , 0 ) ).to.not.be.ok()
    expect( is.sameType( [] , new Number() ) ).to.not.be.ok()
    expect( is.sameType( [] , '' ) ).to.not.be.ok()
    expect( is.sameType( [] , new String() ) ).to.not.be.ok()
    expect( is.sameType( [] , true ) ).to.not.be.ok()
    expect( is.sameType( [] , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( [] , {} ) ).to.not.be.ok()
    expect( is.sameType( [] , [] ) ).to.be.ok()
    expect( is.sameType( [] , function () {} ) ).to.not.be.ok()
    expect( is.sameType( [] , new Date() ) ).to.not.be.ok()
    expect( is.sameType( [] , new Error() ) ).to.not.be.ok()
    expect( is.sameType( [] , /^/ ) ).to.not.be.ok()

    expect( is.sameType( function () {} , null ) ).to.not.be.ok()
    expect( is.sameType( function () {} , void 0 ) ).to.not.be.ok()
    expect( is.sameType( function () {} , 0 ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new Number() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , '' ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new String() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , true ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , {} ) ).to.not.be.ok()
    expect( is.sameType( function () {} , [] ) ).to.not.be.ok()
    expect( is.sameType( function () {} , function () {} ) ).to.be.ok()
    expect( is.sameType( function () {} , new Date() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new Error() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Date() , null ) ).to.not.be.ok()
    expect( is.sameType( new Date() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Date() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , true ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Date() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Date() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new Date() ) ).to.be.ok()
    expect( is.sameType( new Date() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Error() , null ) ).to.not.be.ok()
    expect( is.sameType( new Error() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Error() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , true ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Error() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Error() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Error() ) ).to.be.ok()
    expect( is.sameType( new Error() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( /^/ , null ) ).to.not.be.ok()
    expect( is.sameType( /^/ , void 0 ) ).to.not.be.ok()
    expect( is.sameType( /^/ , 0 ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Number() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , '' ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new String() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , true ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , {} ) ).to.not.be.ok()
    expect( is.sameType( /^/ , [] ) ).to.not.be.ok()
    expect( is.sameType( /^/ , function () {} ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Date() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Error() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , /^/ ) ).to.be.ok()

  } )

  it( 'is.primitive' , function () {

    expect( is.primitive( null ) ).to.be.ok()
    expect( is.primitive( void 0 ) ).to.be.ok()
    expect( is.primitive( 0 ) ).to.be.ok()
    expect( is.primitive( new Number( 0 ) ) ).to.not.be.ok()
    expect( is.primitive( '' ) ).to.be.ok()
    expect( is.primitive( new String( '' ) ) ).to.not.be.ok()
    expect( is.primitive( true ) ).to.be.ok()
    expect( is.primitive( false ) ).to.be.ok()
    expect( is.primitive( new Boolean( true ) ) ).to.not.be.ok()
    expect( is.primitive( new Boolean( false ) ) ).to.not.be.ok()
    expect( is.primitive( {} ) ).to.not.be.ok()
    expect( is.primitive( [] ) ).to.not.be.ok()
    expect( is.primitive( function () {} ) ).to.not.be.ok()

    if ( typeof Symbol === 'function' ) {
      expect( is.primitive( Symbol() ) ).to.be.ok()
      expect( is.primitive( Symbol[ 'for' ]( 'is' ) ) ).to.be.ok()
    }

  } )

  it( 'is.date' , function () {
    expect( is.date( new Date() ) ).to.be.ok()
  } )

  it.skip( 'is.error' , function () {
    expect( is.error( new Error() ) ).to.be.ok()
    expect( is.error( new EvalError() ) ).to.be.ok()
    expect( is.error( new RangeError() ) ).to.be.ok()
    expect( is.error( new ReferenceError() ) ).to.be.ok()
    expect( is.error( new SyntaxError() ) ).to.be.ok()
    expect( is.error( new TypeError() ) ).to.be.ok()
    expect( is.error( new URIError() ) ).to.be.ok()
  } )

  it( 'is.function' , function () {
    expect( is[ 'function' ]( function () {} ) ).to.be.ok()
    expect( is[ 'function' ]( new Function() ) ).to.be.ok() // eslint-disable-line no-new-func
  } )

  it( 'is.map' , function () {
    if ( typeof Map === 'function' ) {
      expect( is.map( new Map() ) ).to.be.ok()
    }
  } )

  it( 'is.regexp' , function () {
    expect( is.regexp( /^/ ) ).to.be.ok()
    expect( is.regexp( new RegExp() ) ).to.be.ok()
  } )

  it( 'is.set' , function () {
    if ( typeof Set === 'function' ) {
      expect( is.set( new Set() ) ).to.be.ok()
    }
  } )

  it( 'is.symbol' , function () {
    if ( typeof Symbol === 'function' ) {
      expect( is.symbol( Symbol() ) ).to.be.ok()
      expect( is.symbol( Symbol[ 'for' ]( 'is' ) ) ).to.be.ok()
    }
  } )

} )
