/* global expect, is */
/* eslint-env mocha */
/* eslint no-empty-function: 0, no-new-wrappers: 0, no-unused-expressions: 0 */

describe( 'bundle:type' , function () {

  it( 'is.sameType' , function () {

    expect( is.sameType( null , null ) ).to.be.ok()
    expect( is.sameType( null , void 0 ) ).to.not.be.ok()
    expect( is.sameType( null , 0 ) ).to.not.be.ok()
    expect( is.sameType( null , new Number() ) ).to.not.be.ok()
    expect( is.sameType( null , '' ) ).to.not.be.ok()
    expect( is.sameType( null , new String() ) ).to.not.be.ok()
    expect( is.sameType( null , true ) ).to.not.be.ok()
    expect( is.sameType( null , false ) ).to.not.be.ok()
    expect( is.sameType( null , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( null , {} ) ).to.not.be.ok()
    expect( is.sameType( null , [] ) ).to.not.be.ok()
    expect( is.sameType( null , arguments ) ).to.not.be.ok()
    expect( is.sameType( null , function () {} ) ).to.not.be.ok()
    expect( is.sameType( null , new Date() ) ).to.not.be.ok()
    expect( is.sameType( null , new Error() ) ).to.not.be.ok()
    expect( is.sameType( null , /^/ ) ).to.not.be.ok()

    expect( is.sameType( void 0 , null ) ).to.not.be.ok()
    expect( is.sameType( void 0 , void 0 ) ).to.be.ok()
    expect( is.sameType( void 0 , 0 ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Number() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , '' ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new String() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , true ) ).to.not.be.ok()
    expect( is.sameType( void 0 , false ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , {} ) ).to.not.be.ok()
    expect( is.sameType( void 0 , [] ) ).to.not.be.ok()
    expect( is.sameType( void 0 , arguments ) ).to.not.be.ok()
    expect( is.sameType( void 0 , function () {} ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Date() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , new Error() ) ).to.not.be.ok()
    expect( is.sameType( void 0 , /^/ ) ).to.not.be.ok()

    expect( is.sameType( 0 , null ) ).to.not.be.ok()
    expect( is.sameType( 0 , void 0 ) ).to.not.be.ok()
    expect( is.sameType( 0 , 0 ) ).to.be.ok()
    expect( is.sameType( 0 , new Number() ) ).to.not.be.ok()
    expect( is.sameType( 0 , '' ) ).to.not.be.ok()
    expect( is.sameType( 0 , new String() ) ).to.not.be.ok()
    expect( is.sameType( 0 , true ) ).to.not.be.ok()
    expect( is.sameType( 0 , false ) ).to.not.be.ok()
    expect( is.sameType( 0 , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( 0 , {} ) ).to.not.be.ok()
    expect( is.sameType( 0 , [] ) ).to.not.be.ok()
    expect( is.sameType( 0 , arguments ) ).to.not.be.ok()
    expect( is.sameType( 0 , function () {} ) ).to.not.be.ok()
    expect( is.sameType( 0 , new Date() ) ).to.not.be.ok()
    expect( is.sameType( 0 , new Error() ) ).to.not.be.ok()
    expect( is.sameType( 0 , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Number() , null ) ).to.not.be.ok()
    expect( is.sameType( new Number() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Number() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Number() ) ).to.be.ok()
    expect( is.sameType( new Number() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , true ) ).to.not.be.ok()
    expect( is.sameType( new Number() , false ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Number() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Number() , arguments ) ).to.not.be.ok()
    expect( is.sameType( new Number() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new Number() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( '' , null ) ).to.not.be.ok()
    expect( is.sameType( '' , void 0 ) ).to.not.be.ok()
    expect( is.sameType( '' , 0 ) ).to.not.be.ok()
    expect( is.sameType( '' , new Number() ) ).to.not.be.ok()
    expect( is.sameType( '' , '' ) ).to.be.ok()
    expect( is.sameType( '' , new String() ) ).to.not.be.ok()
    expect( is.sameType( '' , true ) ).to.not.be.ok()
    expect( is.sameType( '' , false ) ).to.not.be.ok()
    expect( is.sameType( '' , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( '' , {} ) ).to.not.be.ok()
    expect( is.sameType( '' , [] ) ).to.not.be.ok()
    expect( is.sameType( '' , arguments ) ).to.not.be.ok()
    expect( is.sameType( '' , function () {} ) ).to.not.be.ok()
    expect( is.sameType( '' , new Date() ) ).to.not.be.ok()
    expect( is.sameType( '' , new Error() ) ).to.not.be.ok()
    expect( is.sameType( '' , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new String() , null ) ).to.not.be.ok()
    expect( is.sameType( new String() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new String() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new String() , '' ) ).to.not.be.ok()
    expect( is.sameType( new String() , new String() ) ).to.be.ok()
    expect( is.sameType( new String() , true ) ).to.not.be.ok()
    expect( is.sameType( new String() , false ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new String() , {} ) ).to.not.be.ok()
    expect( is.sameType( new String() , [] ) ).to.not.be.ok()
    expect( is.sameType( new String() , arguments ) ).to.not.be.ok()
    expect( is.sameType( new String() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new String() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new String() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( true , null ) ).to.not.be.ok()
    expect( is.sameType( true , void 0 ) ).to.not.be.ok()
    expect( is.sameType( true , 0 ) ).to.not.be.ok()
    expect( is.sameType( true , new Number() ) ).to.not.be.ok()
    expect( is.sameType( true , '' ) ).to.not.be.ok()
    expect( is.sameType( true , new String() ) ).to.not.be.ok()
    expect( is.sameType( true , true ) ).to.be.ok()
    expect( is.sameType( true , false ) ).to.be.ok()
    expect( is.sameType( true , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( true , {} ) ).to.not.be.ok()
    expect( is.sameType( true , [] ) ).to.not.be.ok()
    expect( is.sameType( true , arguments ) ).to.not.be.ok()
    expect( is.sameType( true , function () {} ) ).to.not.be.ok()
    expect( is.sameType( true , new Date() ) ).to.not.be.ok()
    expect( is.sameType( true , new Error() ) ).to.not.be.ok()
    expect( is.sameType( true , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Boolean() , null ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , true ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , false ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Boolean() ) ).to.be.ok()
    expect( is.sameType( new Boolean() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , arguments ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new Boolean() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( {} , null ) ).to.not.be.ok()
    expect( is.sameType( {} , void 0 ) ).to.not.be.ok()
    expect( is.sameType( {} , 0 ) ).to.not.be.ok()
    expect( is.sameType( {} , new Number() ) ).to.not.be.ok()
    expect( is.sameType( {} , '' ) ).to.not.be.ok()
    expect( is.sameType( {} , new String() ) ).to.not.be.ok()
    expect( is.sameType( {} , true ) ).to.not.be.ok()
    expect( is.sameType( {} , false ) ).to.not.be.ok()
    expect( is.sameType( {} , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( {} , {} ) ).to.be.ok()
    expect( is.sameType( {} , [] ) ).to.not.be.ok()
    expect( is.sameType( {} , arguments ) ).to.not.be.ok()
    expect( is.sameType( {} , function () {} ) ).to.not.be.ok()
    expect( is.sameType( {} , new Date() ) ).to.not.be.ok()
    expect( is.sameType( {} , new Error() ) ).to.not.be.ok()
    expect( is.sameType( {} , /^/ ) ).to.not.be.ok()

    expect( is.sameType( [] , null ) ).to.not.be.ok()
    expect( is.sameType( [] , void 0 ) ).to.not.be.ok()
    expect( is.sameType( [] , 0 ) ).to.not.be.ok()
    expect( is.sameType( [] , new Number() ) ).to.not.be.ok()
    expect( is.sameType( [] , '' ) ).to.not.be.ok()
    expect( is.sameType( [] , new String() ) ).to.not.be.ok()
    expect( is.sameType( [] , true ) ).to.not.be.ok()
    expect( is.sameType( [] , false ) ).to.not.be.ok()
    expect( is.sameType( [] , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( [] , {} ) ).to.not.be.ok()
    expect( is.sameType( [] , [] ) ).to.be.ok()
    expect( is.sameType( [] , arguments ) ).to.not.be.ok()
    expect( is.sameType( [] , function () {} ) ).to.not.be.ok()
    expect( is.sameType( [] , new Date() ) ).to.not.be.ok()
    expect( is.sameType( [] , new Error() ) ).to.not.be.ok()
    expect( is.sameType( [] , /^/ ) ).to.not.be.ok()

    expect( is.sameType( arguments , null ) ).to.not.be.ok()
    expect( is.sameType( arguments , void 0 ) ).to.not.be.ok()
    expect( is.sameType( arguments , 0 ) ).to.not.be.ok()
    expect( is.sameType( arguments , new Number() ) ).to.not.be.ok()
    expect( is.sameType( arguments , '' ) ).to.not.be.ok()
    expect( is.sameType( arguments , new String() ) ).to.not.be.ok()
    expect( is.sameType( arguments , true ) ).to.not.be.ok()
    expect( is.sameType( arguments , false ) ).to.not.be.ok()
    expect( is.sameType( arguments , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( arguments , {} ) ).to.not.be.ok()
    expect( is.sameType( arguments , [] ) ).to.not.be.ok()
    expect( is.sameType( arguments , arguments ) ).to.be.ok()
    expect( is.sameType( arguments , function () {} ) ).to.not.be.ok()
    expect( is.sameType( arguments , new Date() ) ).to.not.be.ok()
    expect( is.sameType( arguments , new Error() ) ).to.not.be.ok()
    expect( is.sameType( arguments , /^/ ) ).to.not.be.ok()

    expect( is.sameType( function () {} , null ) ).to.not.be.ok()
    expect( is.sameType( function () {} , void 0 ) ).to.not.be.ok()
    expect( is.sameType( function () {} , 0 ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new Number() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , '' ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new String() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , true ) ).to.not.be.ok()
    expect( is.sameType( function () {} , false ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , {} ) ).to.not.be.ok()
    expect( is.sameType( function () {} , [] ) ).to.not.be.ok()
    expect( is.sameType( function () {} , arguments ) ).to.not.be.ok()
    expect( is.sameType( function () {} , function () {} ) ).to.be.ok()
    expect( is.sameType( function () {} , new Date() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , new Error() ) ).to.not.be.ok()
    expect( is.sameType( function () {} , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Date() , null ) ).to.not.be.ok()
    expect( is.sameType( new Date() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Date() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , true ) ).to.not.be.ok()
    expect( is.sameType( new Date() , false ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Date() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Date() , arguments ) ).to.not.be.ok()
    expect( is.sameType( new Date() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Date() , new Date() ) ).to.be.ok()
    expect( is.sameType( new Date() , new Error() ) ).to.not.be.ok()
    expect( is.sameType( new Date() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( new Error() , null ) ).to.not.be.ok()
    expect( is.sameType( new Error() , void 0 ) ).to.not.be.ok()
    expect( is.sameType( new Error() , 0 ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Number() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , '' ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new String() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , true ) ).to.not.be.ok()
    expect( is.sameType( new Error() , false ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , {} ) ).to.not.be.ok()
    expect( is.sameType( new Error() , [] ) ).to.not.be.ok()
    expect( is.sameType( new Error() , arguments ) ).to.not.be.ok()
    expect( is.sameType( new Error() , function () {} ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Date() ) ).to.not.be.ok()
    expect( is.sameType( new Error() , new Error() ) ).to.be.ok()
    expect( is.sameType( new Error() , /^/ ) ).to.not.be.ok()

    expect( is.sameType( /^/ , null ) ).to.not.be.ok()
    expect( is.sameType( /^/ , void 0 ) ).to.not.be.ok()
    expect( is.sameType( /^/ , 0 ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Number() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , '' ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new String() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , true ) ).to.not.be.ok()
    expect( is.sameType( /^/ , false ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Boolean() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , {} ) ).to.not.be.ok()
    expect( is.sameType( /^/ , [] ) ).to.not.be.ok()
    expect( is.sameType( /^/ , arguments ) ).to.not.be.ok()
    expect( is.sameType( /^/ , function () {} ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Date() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , new Error() ) ).to.not.be.ok()
    expect( is.sameType( /^/ , /^/ ) ).to.be.ok()

    expect( is.not.sameType( null , null ) ).to.not.be.ok()
    expect( is.not.sameType( null , void 0 ) ).to.be.ok()
    expect( is.not.sameType( null , 0 ) ).to.be.ok()
    expect( is.not.sameType( null , new Number() ) ).to.be.ok()
    expect( is.not.sameType( null , '' ) ).to.be.ok()
    expect( is.not.sameType( null , new String() ) ).to.be.ok()
    expect( is.not.sameType( null , true ) ).to.be.ok()
    expect( is.not.sameType( null , false ) ).to.be.ok()
    expect( is.not.sameType( null , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( null , {} ) ).to.be.ok()
    expect( is.not.sameType( null , [] ) ).to.be.ok()
    expect( is.not.sameType( null , arguments ) ).to.be.ok()
    expect( is.not.sameType( null , function () {} ) ).to.be.ok()
    expect( is.not.sameType( null , new Date() ) ).to.be.ok()
    expect( is.not.sameType( null , new Error() ) ).to.be.ok()
    expect( is.not.sameType( null , /^/ ) ).to.be.ok()

    expect( is.not.sameType( void 0 , null ) ).to.be.ok()
    expect( is.not.sameType( void 0 , void 0 ) ).to.not.be.ok()
    expect( is.not.sameType( void 0 , 0 ) ).to.be.ok()
    expect( is.not.sameType( void 0 , new Number() ) ).to.be.ok()
    expect( is.not.sameType( void 0 , '' ) ).to.be.ok()
    expect( is.not.sameType( void 0 , new String() ) ).to.be.ok()
    expect( is.not.sameType( void 0 , true ) ).to.be.ok()
    expect( is.not.sameType( void 0 , false ) ).to.be.ok()
    expect( is.not.sameType( void 0 , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( void 0 , {} ) ).to.be.ok()
    expect( is.not.sameType( void 0 , [] ) ).to.be.ok()
    expect( is.not.sameType( void 0 , arguments ) ).to.be.ok()
    expect( is.not.sameType( void 0 , function () {} ) ).to.be.ok()
    expect( is.not.sameType( void 0 , new Date() ) ).to.be.ok()
    expect( is.not.sameType( void 0 , new Error() ) ).to.be.ok()
    expect( is.not.sameType( void 0 , /^/ ) ).to.be.ok()

    expect( is.not.sameType( 0 , null ) ).to.be.ok()
    expect( is.not.sameType( 0 , void 0 ) ).to.be.ok()
    expect( is.not.sameType( 0 , 0 ) ).to.not.be.ok()
    expect( is.not.sameType( 0 , new Number() ) ).to.be.ok()
    expect( is.not.sameType( 0 , '' ) ).to.be.ok()
    expect( is.not.sameType( 0 , new String() ) ).to.be.ok()
    expect( is.not.sameType( 0 , true ) ).to.be.ok()
    expect( is.not.sameType( 0 , false ) ).to.be.ok()
    expect( is.not.sameType( 0 , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( 0 , {} ) ).to.be.ok()
    expect( is.not.sameType( 0 , [] ) ).to.be.ok()
    expect( is.not.sameType( 0 , arguments ) ).to.be.ok()
    expect( is.not.sameType( 0 , function () {} ) ).to.be.ok()
    expect( is.not.sameType( 0 , new Date() ) ).to.be.ok()
    expect( is.not.sameType( 0 , new Error() ) ).to.be.ok()
    expect( is.not.sameType( 0 , /^/ ) ).to.be.ok()

    expect( is.not.sameType( new Number() , null ) ).to.be.ok()
    expect( is.not.sameType( new Number() , void 0 ) ).to.be.ok()
    expect( is.not.sameType( new Number() , 0 ) ).to.be.ok()
    expect( is.not.sameType( new Number() , new Number() ) ).to.not.be.ok()
    expect( is.not.sameType( new Number() , '' ) ).to.be.ok()
    expect( is.not.sameType( new Number() , new String() ) ).to.be.ok()
    expect( is.not.sameType( new Number() , true ) ).to.be.ok()
    expect( is.not.sameType( new Number() , false ) ).to.be.ok()
    expect( is.not.sameType( new Number() , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( new Number() , {} ) ).to.be.ok()
    expect( is.not.sameType( new Number() , [] ) ).to.be.ok()
    expect( is.not.sameType( new Number() , arguments ) ).to.be.ok()
    expect( is.not.sameType( new Number() , function () {} ) ).to.be.ok()
    expect( is.not.sameType( new Number() , new Date() ) ).to.be.ok()
    expect( is.not.sameType( new Number() , new Error() ) ).to.be.ok()
    expect( is.not.sameType( new Number() , /^/ ) ).to.be.ok()

    expect( is.not.sameType( '' , null ) ).to.be.ok()
    expect( is.not.sameType( '' , void 0 ) ).to.be.ok()
    expect( is.not.sameType( '' , 0 ) ).to.be.ok()
    expect( is.not.sameType( '' , new Number() ) ).to.be.ok()
    expect( is.not.sameType( '' , '' ) ).to.not.be.ok()
    expect( is.not.sameType( '' , new String() ) ).to.be.ok()
    expect( is.not.sameType( '' , true ) ).to.be.ok()
    expect( is.not.sameType( '' , false ) ).to.be.ok()
    expect( is.not.sameType( '' , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( '' , {} ) ).to.be.ok()
    expect( is.not.sameType( '' , [] ) ).to.be.ok()
    expect( is.not.sameType( '' , arguments ) ).to.be.ok()
    expect( is.not.sameType( '' , function () {} ) ).to.be.ok()
    expect( is.not.sameType( '' , new Date() ) ).to.be.ok()
    expect( is.not.sameType( '' , new Error() ) ).to.be.ok()
    expect( is.not.sameType( '' , /^/ ) ).to.be.ok()

    expect( is.not.sameType( new String() , null ) ).to.be.ok()
    expect( is.not.sameType( new String() , void 0 ) ).to.be.ok()
    expect( is.not.sameType( new String() , 0 ) ).to.be.ok()
    expect( is.not.sameType( new String() , new Number() ) ).to.be.ok()
    expect( is.not.sameType( new String() , '' ) ).to.be.ok()
    expect( is.not.sameType( new String() , new String() ) ).to.not.be.ok()
    expect( is.not.sameType( new String() , true ) ).to.be.ok()
    expect( is.not.sameType( new String() , false ) ).to.be.ok()
    expect( is.not.sameType( new String() , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( new String() , {} ) ).to.be.ok()
    expect( is.not.sameType( new String() , [] ) ).to.be.ok()
    expect( is.not.sameType( new String() , arguments ) ).to.be.ok()
    expect( is.not.sameType( new String() , function () {} ) ).to.be.ok()
    expect( is.not.sameType( new String() , new Date() ) ).to.be.ok()
    expect( is.not.sameType( new String() , new Error() ) ).to.be.ok()
    expect( is.not.sameType( new String() , /^/ ) ).to.be.ok()

    expect( is.not.sameType( true , null ) ).to.be.ok()
    expect( is.not.sameType( true , void 0 ) ).to.be.ok()
    expect( is.not.sameType( true , 0 ) ).to.be.ok()
    expect( is.not.sameType( true , new Number() ) ).to.be.ok()
    expect( is.not.sameType( true , '' ) ).to.be.ok()
    expect( is.not.sameType( true , new String() ) ).to.be.ok()
    expect( is.not.sameType( true , true ) ).to.not.be.ok()
    expect( is.not.sameType( true , false ) ).to.not.be.ok()
    expect( is.not.sameType( true , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( true , {} ) ).to.be.ok()
    expect( is.not.sameType( true , [] ) ).to.be.ok()
    expect( is.not.sameType( true , arguments ) ).to.be.ok()
    expect( is.not.sameType( true , function () {} ) ).to.be.ok()
    expect( is.not.sameType( true , new Date() ) ).to.be.ok()
    expect( is.not.sameType( true , new Error() ) ).to.be.ok()
    expect( is.not.sameType( true , /^/ ) ).to.be.ok()

    expect( is.not.sameType( new Boolean() , null ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , void 0 ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , 0 ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , new Number() ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , '' ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , new String() ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , true ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , false ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , new Boolean() ) ).to.not.be.ok()
    expect( is.not.sameType( new Boolean() , {} ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , [] ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , arguments ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , function () {} ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , new Date() ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , new Error() ) ).to.be.ok()
    expect( is.not.sameType( new Boolean() , /^/ ) ).to.be.ok()

    expect( is.not.sameType( {} , null ) ).to.be.ok()
    expect( is.not.sameType( {} , void 0 ) ).to.be.ok()
    expect( is.not.sameType( {} , 0 ) ).to.be.ok()
    expect( is.not.sameType( {} , new Number() ) ).to.be.ok()
    expect( is.not.sameType( {} , '' ) ).to.be.ok()
    expect( is.not.sameType( {} , new String() ) ).to.be.ok()
    expect( is.not.sameType( {} , true ) ).to.be.ok()
    expect( is.not.sameType( {} , false ) ).to.be.ok()
    expect( is.not.sameType( {} , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( {} , {} ) ).to.not.be.ok()
    expect( is.not.sameType( {} , [] ) ).to.be.ok()
    expect( is.not.sameType( {} , arguments ) ).to.be.ok()
    expect( is.not.sameType( {} , function () {} ) ).to.be.ok()
    expect( is.not.sameType( {} , new Date() ) ).to.be.ok()
    expect( is.not.sameType( {} , new Error() ) ).to.be.ok()
    expect( is.not.sameType( {} , /^/ ) ).to.be.ok()

    expect( is.not.sameType( [] , null ) ).to.be.ok()
    expect( is.not.sameType( [] , void 0 ) ).to.be.ok()
    expect( is.not.sameType( [] , 0 ) ).to.be.ok()
    expect( is.not.sameType( [] , new Number() ) ).to.be.ok()
    expect( is.not.sameType( [] , '' ) ).to.be.ok()
    expect( is.not.sameType( [] , new String() ) ).to.be.ok()
    expect( is.not.sameType( [] , true ) ).to.be.ok()
    expect( is.not.sameType( [] , false ) ).to.be.ok()
    expect( is.not.sameType( [] , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( [] , {} ) ).to.be.ok()
    expect( is.not.sameType( [] , [] ) ).to.not.be.ok()
    expect( is.not.sameType( [] , arguments ) ).to.be.ok()
    expect( is.not.sameType( [] , function () {} ) ).to.be.ok()
    expect( is.not.sameType( [] , new Date() ) ).to.be.ok()
    expect( is.not.sameType( [] , new Error() ) ).to.be.ok()
    expect( is.not.sameType( [] , /^/ ) ).to.be.ok()

    expect( is.not.sameType( arguments , null ) ).to.be.ok()
    expect( is.not.sameType( arguments , void 0 ) ).to.be.ok()
    expect( is.not.sameType( arguments , 0 ) ).to.be.ok()
    expect( is.not.sameType( arguments , new Number() ) ).to.be.ok()
    expect( is.not.sameType( arguments , '' ) ).to.be.ok()
    expect( is.not.sameType( arguments , new String() ) ).to.be.ok()
    expect( is.not.sameType( arguments , true ) ).to.be.ok()
    expect( is.not.sameType( arguments , false ) ).to.be.ok()
    expect( is.not.sameType( arguments , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( arguments , {} ) ).to.be.ok()
    expect( is.not.sameType( arguments , [] ) ).to.be.ok()
    expect( is.not.sameType( arguments , arguments ) ).to.not.be.ok()
    expect( is.not.sameType( arguments , function () {} ) ).to.be.ok()
    expect( is.not.sameType( arguments , new Date() ) ).to.be.ok()
    expect( is.not.sameType( arguments , new Error() ) ).to.be.ok()
    expect( is.not.sameType( arguments , /^/ ) ).to.be.ok()

    expect( is.not.sameType( function () {} , null ) ).to.be.ok()
    expect( is.not.sameType( function () {} , void 0 ) ).to.be.ok()
    expect( is.not.sameType( function () {} , 0 ) ).to.be.ok()
    expect( is.not.sameType( function () {} , new Number() ) ).to.be.ok()
    expect( is.not.sameType( function () {} , '' ) ).to.be.ok()
    expect( is.not.sameType( function () {} , new String() ) ).to.be.ok()
    expect( is.not.sameType( function () {} , true ) ).to.be.ok()
    expect( is.not.sameType( function () {} , false ) ).to.be.ok()
    expect( is.not.sameType( function () {} , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( function () {} , {} ) ).to.be.ok()
    expect( is.not.sameType( function () {} , [] ) ).to.be.ok()
    expect( is.not.sameType( function () {} , arguments ) ).to.be.ok()
    expect( is.not.sameType( function () {} , function () {} ) ).to.not.be.ok()
    expect( is.not.sameType( function () {} , new Date() ) ).to.be.ok()
    expect( is.not.sameType( function () {} , new Error() ) ).to.be.ok()
    expect( is.not.sameType( function () {} , /^/ ) ).to.be.ok()

    expect( is.not.sameType( new Date() , null ) ).to.be.ok()
    expect( is.not.sameType( new Date() , void 0 ) ).to.be.ok()
    expect( is.not.sameType( new Date() , 0 ) ).to.be.ok()
    expect( is.not.sameType( new Date() , new Number() ) ).to.be.ok()
    expect( is.not.sameType( new Date() , '' ) ).to.be.ok()
    expect( is.not.sameType( new Date() , new String() ) ).to.be.ok()
    expect( is.not.sameType( new Date() , true ) ).to.be.ok()
    expect( is.not.sameType( new Date() , false ) ).to.be.ok()
    expect( is.not.sameType( new Date() , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( new Date() , {} ) ).to.be.ok()
    expect( is.not.sameType( new Date() , [] ) ).to.be.ok()
    expect( is.not.sameType( new Date() , arguments ) ).to.be.ok()
    expect( is.not.sameType( new Date() , function () {} ) ).to.be.ok()
    expect( is.not.sameType( new Date() , new Date() ) ).to.not.be.ok()
    expect( is.not.sameType( new Date() , new Error() ) ).to.be.ok()
    expect( is.not.sameType( new Date() , /^/ ) ).to.be.ok()

    expect( is.not.sameType( new Error() , null ) ).to.be.ok()
    expect( is.not.sameType( new Error() , void 0 ) ).to.be.ok()
    expect( is.not.sameType( new Error() , 0 ) ).to.be.ok()
    expect( is.not.sameType( new Error() , new Number() ) ).to.be.ok()
    expect( is.not.sameType( new Error() , '' ) ).to.be.ok()
    expect( is.not.sameType( new Error() , new String() ) ).to.be.ok()
    expect( is.not.sameType( new Error() , true ) ).to.be.ok()
    expect( is.not.sameType( new Error() , false ) ).to.be.ok()
    expect( is.not.sameType( new Error() , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( new Error() , {} ) ).to.be.ok()
    expect( is.not.sameType( new Error() , [] ) ).to.be.ok()
    expect( is.not.sameType( new Error() , arguments ) ).to.be.ok()
    expect( is.not.sameType( new Error() , function () {} ) ).to.be.ok()
    expect( is.not.sameType( new Error() , new Date() ) ).to.be.ok()
    expect( is.not.sameType( new Error() , new Error() ) ).to.not.be.ok()
    expect( is.not.sameType( new Error() , /^/ ) ).to.be.ok()

    expect( is.not.sameType( /^/ , null ) ).to.be.ok()
    expect( is.not.sameType( /^/ , void 0 ) ).to.be.ok()
    expect( is.not.sameType( /^/ , 0 ) ).to.be.ok()
    expect( is.not.sameType( /^/ , new Number() ) ).to.be.ok()
    expect( is.not.sameType( /^/ , '' ) ).to.be.ok()
    expect( is.not.sameType( /^/ , new String() ) ).to.be.ok()
    expect( is.not.sameType( /^/ , true ) ).to.be.ok()
    expect( is.not.sameType( /^/ , false ) ).to.be.ok()
    expect( is.not.sameType( /^/ , new Boolean() ) ).to.be.ok()
    expect( is.not.sameType( /^/ , {} ) ).to.be.ok()
    expect( is.not.sameType( /^/ , [] ) ).to.be.ok()
    expect( is.not.sameType( /^/ , arguments ) ).to.be.ok()
    expect( is.not.sameType( /^/ , function () {} ) ).to.be.ok()
    expect( is.not.sameType( /^/ , new Date() ) ).to.be.ok()
    expect( is.not.sameType( /^/ , new Error() ) ).to.be.ok()
    expect( is.not.sameType( /^/ , /^/ ) ).to.not.be.ok()

  } )

} )
